# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell (hyperpolymath)
#
# Exclude verbatim licence texts from SonarCloud analysis. LICENSE and the
# LICENSES/*.txt files are boilerplate licence text, not source code, and the
# canonical layout requires the root LICENSE to be byte-identical to
# LICENSES/AGPL-3.0-or-later.txt — which otherwise trips SonarCloud's
# "duplication on new code" quality gate (the MPL repos carry the same
# duplication by design).
sonar.exclusions=LICENSE,LICENSES/**
sonar.cpd.exclusions=LICENSE,LICENSES/**
