// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell (hyperpolymath)
//
// make_vectors.js — (re)generate sim/vectors/shadow_v1.json from the reference twin.
//   bun run vectors          write the file
//   bun run vectors:check    fail if the committed file differs (drift guard; also run in test/vectors_test.js)
//
// The vectors pin WHAT THE MODEL DOES (checkpoint hashes every 100 steps + the final state).  Any
// implementation of ABI v1 — the JS twin, an AffineScript->WASM build, a future rewrite — must reproduce them.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { initState, stepState, FIELDS } from "./shadow_ref.js";
import { SCENARIOS, inputFor } from "./scenarios.js";

const HERE = dirname(fileURLToPath(import.meta.url));
export const VECTOR_PATH = resolve(HERE, "vectors/shadow_v1.json");

function fnv1a32(ints) {
  let h = 0x811c9dc5;
  for (const v of ints) {
    for (let b = 0; b < 4; b++) { h ^= (v >>> (8 * b)) & 0xff; h = Math.imul(h, 0x01000193) >>> 0; }
  }
  return h.toString(16).padStart(8, "0");
}

export function buildVectors() {
  const scenarios = SCENARIOS.map((sc) => {
    let s = initState();
    const checkpoints = {};
    for (let n = 0; n < sc.steps; n++) {
      s = stepState(s, inputFor(sc, n));
      if ((n + 1) % 100 === 0) checkpoints[n + 1] = fnv1a32(s);
    }
    return { name: sc.name, steps: sc.steps, script: sc.script, checkpoints, final: s };
  });
  return {
    abi: "1.0.0",
    note: "Generated by sim/make_vectors.js from sim/shadow_ref.js — do not hand-edit. Hash = FNV-1a/32 over the 29 state ints as little-endian i32.",
    fields: FIELDS,
    init: initState(),
    init_hash: fnv1a32(initState()),
    scenarios,
  };
}

export const render = (v) => JSON.stringify(v, null, 1) + "\n";

if (import.meta.main) {
  const fresh = render(buildVectors());
  if (process.argv.includes("--check")) {
    const committed = readFileSync(VECTOR_PATH, "utf8");
    if (committed !== fresh) { console.error("sim/vectors/shadow_v1.json is stale: run `bun run vectors`"); process.exit(1); }
    console.log("vectors up to date");
  } else {
    writeFileSync(VECTOR_PATH, fresh);
    console.log(`wrote ${VECTOR_PATH}`);
  }
}
