// SPDX-License-Identifier: AGPL-3.0-or-later
// SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell (hyperpolymath)
//
// scenarios.js — the golden input scripts.  Pure, integer-only, language-portable: each scenario is
// (name, steps, script) and inputFor() is a few lines any host can reproduce.  The CHECKPOINT hashes
// live in sim/vectors/shadow_v1.json (generated by make_vectors.js) and pin the reference's behaviour.

export const SCENARIOS = Object.freeze([
  { name: "idle",         steps: 600, script: { kind: "const", input: [0, 0, 0, 0, 0] } },
  { name: "climb-right",  steps: 600, script: { kind: "phases", phases: [[0, 300, [1, -1, 0, 0, 0]], [300, 600, [-1, 1, 0, 0, 0]]] } },
  { name: "hold-fire",    steps: 600, script: { kind: "const", input: [0, 0, 1, 0, 0] } },
  { name: "env-toggle",   steps: 600, script: { kind: "phases", phases: [[50, 51, [0, 0, 0, 0, 1]], [51, 52, [0, 0, 0, 0, 1]], [400, 401, [0, 0, 0, 0, 1]]] } },
  { name: "dogfight",     steps: 900, script: { kind: "lcg", seed: 20260929 } },
]);

/** Input for step n of scenario sc: [thrust_x, thrust_y, fire, fire_alt, toggle_env]. */
export function inputFor(sc, n) {
  const s = sc.script;
  if (s.kind === "const") return s.input;
  if (s.kind === "phases") {
    for (const [a, b, inp] of s.phases) if (n >= a && n < b) return inp;
    return [0, 0, 0, 0, 0];
  }
  // lcg: deterministic pseudo-random play, 32-bit LCG (Numerical Recipes), advanced n+1 times from the seed
  let x = s.seed >>> 0;
  for (let i = 0; i <= n; i++) x = (Math.imul(x, 1664525) + 1013904223) >>> 0;
  const r = (x >>> 8);
  return [(r % 3) - 1, ((r >>> 4) % 3) - 1, (r >>> 8) % 10 < 3 ? 1 : 0, (r >>> 12) % 10 < 2 ? 1 : 0, (r >>> 16) % 50 === 0 ? 1 : 0];
}
